create table urlCheck (
id                            bigint PRIMARY KEY generated by default as identity not null,
status_code                   bigint,
title                         varchar(255),
h1                            varchar(255),
description                   clob,
url_id                        bigint REFERENCES url (id),
created_at                    timestamp not null,
);